export default {
  '0e384e19': [() => import(/* webpackChunkName: '0e384e19' */ '@site/docs/intro.md'), '@site/docs/intro.md', require.resolveWeak('@site/docs/intro.md')],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '1f391b9e': [() => import(/* webpackChunkName: '1f391b9e' */ '@theme/MDXPage'), '@theme/MDXPage', require.resolveWeak('@theme/MDXPage')],
  '393be207': [() => import(/* webpackChunkName: '393be207' */ '@site/src/pages/markdown-page.md'), '@site/src/pages/markdown-page.md', require.resolveWeak('@site/src/pages/markdown-page.md')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  'b8a8bbf1': [() => import(/* webpackChunkName: 'b8a8bbf1' */ 'C:\\GitHub\\GitHub-Metrics-Endpoint\\GitHubMetricsDocs\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json'), 'C:\\GitHub\\GitHub-Metrics-Endpoint\\GitHubMetricsDocs\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json', require.resolveWeak('C:\\GitHub\\GitHub-Metrics-Endpoint\\GitHubMetricsDocs\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json')],
  'f77a1a8d': [() => import(/* webpackChunkName: 'f77a1a8d' */ 'C:\\GitHub\\GitHub-Metrics-Endpoint\\GitHubMetricsDocs\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json'), 'C:\\GitHub\\GitHub-Metrics-Endpoint\\GitHubMetricsDocs\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json', require.resolveWeak('C:\\GitHub\\GitHub-Metrics-Endpoint\\GitHubMetricsDocs\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json')],};
